library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
by_year<-group_by(NEI,year)
total<-summarise(by_year,Emissions=sum(Emissions))
png(file="Answer1.png", width=480, height=480)
par(cex.axis=0.7)
with(total, plot(year,Emissions, main="Total Emissions 1999-2008"))
with(total, lines(year,Emissions))
dev.off()