library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
baltimore<-filter(NEI,fips == "24510")
baltimore_by_year<-group_by(baltimore,year)
baltimore_total<-summarise(baltimore_by_year,Emissions=sum(Emissions))
png(file="Answer2.png", width=480, height=480)
par(cex.axis=0.7)
with(baltimore_total, plot(year,Emissions, main="Baltimore Total Emissions 1999-2008"))
with(baltimore_total, lines(year,Emissions))
dev.off()